Fixed bugs in Upload to GCS action

diff --git a/.github/workflows/upload-browser-builds-to-cdn.yaml b/.github/workflows/upload-browser-builds-to-cdn.yaml
--- a/.github/workflows/upload-browser-builds-to-cdn.yaml
+++ b/.github/workflows/upload-browser-builds-to-cdn.yaml
@@ -30,7 +30,19 @@ jobs:
       - name: Debug Browser Build Files
         run: ls -la $GITHUB_WORKSPACE/lib/browser
 
+      - name: Check Google Cloud SDK Presence
+        id: check-gcloud-sdk
+        run: |
+          if command -v gcloud >/dev/null 2>&1; then
+            echo "Google Cloud SDK is already installed."
+            exit 0
+          else
+            echo "Google Cloud SDK not found. Proceeding with installation."
+            exit 1
+          fi
+
       - name: Install Google Cloud SDK
+        if: steps.check-gcloud-sdk.outputs.result == '1'
         run: |
           curl https://sdk.cloud.google.com | bash
           exec -l $SHELL
@@ -55,4 +67,4 @@ jobs:
       - name: Rename and Upload to Google Cloud Storage
         run: |
           VERSION=${{ steps.extract-version.outputs.version }}
-          gsutil -m cp -r $GITHUB_WORKSPACE/lib/browser/* gs://${{ secrets.GCS_BUCKET_NAME }}/mini-digital-sdk.v${VERSION}/
+          gsutil cp /lib/browser/* gs://${{ secrets.GCS_BUCKET_NAME }}/mini-digital-sdk.v${VERSION}/
